### ISSUE TITLE
test_validate_delete_model is producing unexpected error

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_automatic_cockpit_based_testing#60]
**service:** 
https://github.com/Jumpscale/ays_jumpscale8/blob/8.1.1/tests/test_services/test_validate_delete_models/actions.py

**Error**:
```xml
 <testcase classname="/cockpit_testing/Framework/TestCases/test_validate_delete_model.yaml" name="test_validate_delete_model.yaml" time="10.66">
  <error>
   service: instance - Message: ERROR : instance (&lt;class 'JSExceptions.RuntimeError'&gt;, ERROR: Can not copy file, file: /optvar/cockpit_repos/10ed8f9e43/blueprints/test_validate_delete_model_sample.yaml does not exist in system.fs.copyFile ((type:runtime.error))
  </error>
```
**Cockpit Version**
8.1.1

**Comment by ahussein** [comment]
this is not an unexpected.... its a result of moving the bps from the testing repo to the js8_core repo. when the code was written, another blueprint was expected in the same blueprints directory of the same repository. Since now the driver is executing the tests differently we need to figure out a new way to implement the test while keeping the same functionality.

**Comment by islamTaha12** [comment]
@ahussein Please check my commit here
https://github.com/Jumpscale/ays_jumpscale8/commit/170eb33769ca21f2030c36c7434966bf175345f9

The test case is working now so please if u dont have a comment in this fix, close this issue.
